name: ML Pipeline CI

on:
  push:
    branches: [ kernelridge ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train and Test Decision Tree Model
      run: |
        echo "=== Testing Decision Tree Model ==="
        python train.py

    - name: Train and Test Kernel Ridge Model
      run: |
        echo "=== Testing Kernel Ridge Model ==="
        python train2.py
